DROP TABLE IF EXISTS reviews,books,employees,depertments;

CREATE TABLE books(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	book_name VARCHAR(255) NOT NULL,
	author VARCHAR(255),
	publisher VARCHAR(255),
	price INT,
	isbn VARCHAR(50),
	num_of_books INT,
	book_image_url VARCHAR(255),
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE reviews(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	emp_id BIGINT,
	rating BIGINT,
	comment text,
	book_id BIGINT,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (book_id) REFERENCES books(id)
	
);

CREATE TABLE employees(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	emp_name VARCHAR(255),
	emp_id VARCHAR(255),
	password VARCHAR(255),
	dep_id BIGINT,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE depertments(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	dep_name VARCHAR(255),
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);